// ===========================================================================
// The one fetch client.
//
// Every HTTP call in the app goes through here so that failures surface the same
// way wherever they happen: a window `api-error` event the shell turns into a
// toast. A screen that handles its own fetch errors handles them differently
// from the next screen, and the user learns two mental models for "it broke".
// ===========================================================================

import { API_BASE } from './dataSource.js'

/** Thrown for any non-2xx. Carries the service's own code so a caller can branch. */
export class ApiError extends Error {
  constructor(status, code, message, url) {
    super(message || `Request failed (${status})`)
    this.name = 'ApiError'
    this.status = status
    this.code = code
    this.url = url
  }
}

function announce(error) {
  if (typeof window === 'undefined') return
  window.dispatchEvent(new CustomEvent('api-error', { detail: error }))
}

async function request(path, { method = 'GET', body, headers, signal, raw } = {}) {
  const url = path.startsWith('http') ? path : `${API_BASE}${path}`

  const init = { method, signal, headers: { ...headers } }
  if (body instanceof FormData) {
    // Never set Content-Type for FormData — the boundary is generated by fetch,
    // and setting it by hand produces a body the server cannot parse.
    init.body = body
  } else if (body !== undefined) {
    init.headers['Content-Type'] = 'application/json'
    init.body = JSON.stringify(body)
  }

  let response
  try {
    response = await fetch(url, init)
  } catch (cause) {
    // Network-level: the service is down, or the dev proxy has nothing behind it.
    // Worth its own message, because "failed to fetch" sends people debugging the
    // wrong layer.
    const error = new ApiError(0, 'unreachable', `Cannot reach the service at ${url}`, url)
    announce(error)
    throw error
  }

  if (!response.ok) {
    let code = 'error'
    let message = `Request failed (${response.status})`
    try {
      const payload = await response.json()
      code = payload.code ?? code
      message = payload.message ?? message
    } catch {
      // A non-JSON error body — a proxy page, usually. The status is all we have.
    }
    const error = new ApiError(response.status, code, message, url)
    announce(error)
    throw error
  }

  if (raw) return response
  if (response.status === 204) return null
  return response.json()
}

export const api = {
  get: (path, opts) => request(path, { ...opts, method: 'GET' }),
  post: (path, body, opts) => request(path, { ...opts, method: 'POST', body }),
  patch: (path, body, opts) => request(path, { ...opts, method: 'PATCH', body }),
  del: (path, opts) => request(path, { ...opts, method: 'DELETE' }),
  raw: (path, opts) => request(path, { ...opts, raw: true }),

  /**
   * Subscribes to a server-sent event stream.
   *
   * Returns an unsubscribe function with the same shape the mock run engine
   * already has, so the caller does not know which is behind it.
   */
  stream(path, onEvent, { onError } = {}) {
    const source = new EventSource(`${API_BASE}${path}`)

    // One handler, and the type read off the body.
    //
    // This was a list of twelve `addEventListener(type, …)` calls, which is the
    // only shape `EventSource` offers for *named* events — and it has no wildcard,
    // so an event whose name is not on the list is delivered to nobody. That is a
    // silent failure with the worst possible signature: `llm_call` and `llm_cached`
    // reached the tape, so the run log showed them on reload and never live, and
    // the panel looked like the events were missing rather than unsubscribed.
    //
    // So the service stopped naming them and the body carries `type` (it always
    // did — the wire is flat `{seq, type, at, …payload}`). A new event type is now
    // a constant on one side and nothing at all on this one.
    source.onmessage = (e) => {
      let event
      try {
        event = e.data ? JSON.parse(e.data) : null
      } catch {
        return
      }
      if (event && event.type) onEvent(event)
    }
    source.onerror = (e) => {
      // EventSource reconnects on its own; only a closed stream is terminal.
      if (source.readyState === EventSource.CLOSED) onError?.(e)
    }
    return () => source.close()
  },
}
